language: node_js
node_js:
 - "stable"
services:
 - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.8
env:
 - CXX=g++-4.8
install:
 - npm install canvas
 - npm install
before_script:
 - npm install -g gulp
script: 
 - gulp travis
