var fakeUsers = [{"name":"Andrew Day","email":"aday0@nasa.gov"},
{"name":"Margaret Watkins","email":"mwatkins1@loc.gov"},
{"name":"Joseph Perkins","email":"jperkins2@vimeo.com"},
{"name":"Linda Turner","email":"lturner3@cnet.com"},
{"name":"Robert Mendoza","email":"rmendoza4@behance.net"},
{"name":"Larry Burns","email":"lburns5@google.com.hk"},
{"name":"Jesse Ford","email":"jford6@webeden.co.uk"},
{"name":"Elizabeth Reynolds","email":"ereynolds7@tripod.com"},
{"name":"Katherine Simmons","email":"ksimmons8@unc.edu"},
{"name":"Melissa Simmons","email":"msimmons9@amazon.de"},
{"name":"Mark Dixon","email":"mdixona@chronoengine.com"},
{"name":"Eric Ortiz","email":"eortizb@webs.com"},
{"name":"Edward Howard","email":"ehowardc@privacy.gov.au"},
{"name":"Julia Rose","email":"jrosed@virginia.edu"},
{"name":"Dennis Wells","email":"dwellse@bbb.org"},
{"name":"Stephanie Jones","email":"sjonesf@hostgator.com"},
{"name":"Beverly Vasquez","email":"bvasquezg@hao123.com"},
{"name":"Joshua Jacobs","email":"jjacobsh@kickstarter.com"},
{"name":"Rose Mcdonald","email":"rmcdonaldi@webmd.com"},
{"name":"Christine Butler","email":"cbutlerj@intel.com"},
{"name":"Tina Kennedy","email":"tkennedyk@census.gov"},
{"name":"Antonio Chavez","email":"achavezl@youku.com"},
{"name":"Ann Jordan","email":"ajordanm@loc.gov"},
{"name":"Marie Fernandez","email":"mfernandezn@nih.gov"},
{"name":"Howard Fernandez","email":"hfernandezo@1688.com"},
{"name":"Daniel Russell","email":"drussellp@harvard.edu"},
{"name":"Steven Jones","email":"sjonesq@prweb.com"},
{"name":"Stephen Robinson","email":"srobinsonr@purevolume.com"},
{"name":"Carolyn Watkins","email":"cwatkinss@hc360.com"},
{"name":"Janice Stevens","email":"jstevenst@xing.com"},
{"name":"Shirley Gonzalez","email":"sgonzalezu@google.cn"},
{"name":"Henry Gonzalez","email":"hgonzalezv@state.tx.us"},
{"name":"Clarence Coleman","email":"ccolemanw@blogtalkradio.com"},
{"name":"Catherine Bennett","email":"cbennettx@goo.ne.jp"},
{"name":"Jacqueline Hanson","email":"jhansony@cloudflare.com"},
{"name":"Frank Rice","email":"fricez@github.com"},
{"name":"Lisa Owens","email":"lowens10@paypal.com"},
{"name":"Ronald Powell","email":"rpowell11@cloudflare.com"},
{"name":"Brandon Burns","email":"bburns12@sciencedirect.com"},
{"name":"Anna Berry","email":"aberry13@nature.com"},
{"name":"Fred Ellis","email":"fellis14@wikispaces.com"},
{"name":"Brian Roberts","email":"broberts15@fema.gov"},
{"name":"Marie Mcdonald","email":"mmcdonald16@sfgate.com"},
{"name":"Steven Ferguson","email":"sferguson17@miibeian.gov.cn"},
{"name":"Ashley Collins","email":"acollins18@noaa.gov"},
{"name":"Patrick Carpenter","email":"pcarpenter19@163.com"},
{"name":"Mildred Long","email":"mlong1a@altervista.org"},
{"name":"Harold Wells","email":"hwells1b@toplist.cz"},
{"name":"Nicole Boyd","email":"nboyd1c@hc360.com"},
{"name":"Eugene Hunt","email":"ehunt1d@wired.com"}]
var fakeLevels = [{"title":"odio","map":"ZOWYBoZ21VGs", "starCount":Math.floor(Math.random() * 11)},
{"title":"enim blandit mi","map":"aQ5Y5iHGWU", "starCount":Math.floor(Math.random() * 11)},
{"title":"purus","map":"KKNiDC9ZZF", "starCount":Math.floor(Math.random() * 11)},
{"title":"ut massa volutpat convallis","map":"EVl4fIScsjLf", "starCount":Math.floor(Math.random() * 11)},
{"title":"risus semper porta","map":"gXW6YX6", "starCount":Math.floor(Math.random() * 11)},
{"title":"neque","map":"BXAaiARTqM", "starCount":Math.floor(Math.random() * 11)},
{"title":"erat nulla tempus vivamus in","map":"L455ie", "starCount":Math.floor(Math.random() * 11)},
{"title":"quis turpis sed ante vivamus","map":"iRWf2wAOsj", "starCount":Math.floor(Math.random() * 11)},
{"title":"id mauris vulputate elementum nullam","map":"6DXqT4czL8B", "starCount":Math.floor(Math.random() * 11)},
{"title":"amet eros suspendisse accumsan","map":"upA7llmG", "starCount":Math.floor(Math.random() * 11)},
{"title":"lacinia","map":"LdxADXVmy1pQ", "starCount":Math.floor(Math.random() * 11)},
{"title":"suspendisse potenti in eleifend quam","map":"FvbbLq1pbT", "starCount":Math.floor(Math.random() * 11)},
{"title":"dolor","map":"MRYWMP8WlZ", "starCount":Math.floor(Math.random() * 11)},
{"title":"gravida","map":"JnpBoFd6A4s", "starCount":Math.floor(Math.random() * 11)},
{"title":"rhoncus","map":"e8SHhKaylZm", "starCount":Math.floor(Math.random() * 11)},
{"title":"fermentum donec","map":"dSKJv3", "starCount":Math.floor(Math.random() * 11)},
{"title":"scelerisque mauris sit amet eros","map":"fUuNDFXhK", "starCount":Math.floor(Math.random() * 11)},
{"title":"turpis sed ante vivamus tortor","map":"SZARWfxd", "starCount":Math.floor(Math.random() * 11)},
{"title":"ut erat id","map":"lFqKAsNYM", "starCount":Math.floor(Math.random() * 11)},
{"title":"et magnis","map":"o28EZKtDJn", "starCount":Math.floor(Math.random() * 11)},
{"title":"tincidunt nulla mollis molestie lorem","map":"HTKGmlEuq4Y", "starCount":Math.floor(Math.random() * 11)},
{"title":"ante vestibulum","map":"Xy7XCIIsWi", "starCount":Math.floor(Math.random() * 11)},
{"title":"semper sapien a","map":"7TVaF3lqKvQ7", "starCount":Math.floor(Math.random() * 11)},
{"title":"aliquet","map":"d10TZY40ZA", "starCount":Math.floor(Math.random() * 11)},
{"title":"lacus","map":"Yupqip", "starCount":Math.floor(Math.random() * 11)},
{"title":"tellus","map":"YHRTymz", "starCount":Math.floor(Math.random() * 11)},
{"title":"odio odio elementum eu","map":"xUD2GW2", "starCount":Math.floor(Math.random() * 11)},
{"title":"sit amet justo","map":"qTAqlf7lPbj", "starCount":Math.floor(Math.random() * 11)},
{"title":"mi pede","map":"vzpdLGQo5", "starCount":Math.floor(Math.random() * 11)},
{"title":"diam nam","map":"u4aoqvJaRCk", "starCount":Math.floor(Math.random() * 11)},
{"title":"tempus vivamus","map":"pP7lpNIdy6", "starCount":Math.floor(Math.random() * 11)},
{"title":"dui luctus rutrum nulla tellus","map":"RdwD3Y", "starCount":Math.floor(Math.random() * 11)},
{"title":"vestibulum ante ipsum primis","map":"jeE5hiqbDgHT", "starCount":Math.floor(Math.random() * 11)},
{"title":"metus","map":"khs9q0V7", "starCount":Math.floor(Math.random() * 11)},
{"title":"vestibulum ante ipsum","map":"BZzlBoU", "starCount":Math.floor(Math.random() * 11)},
{"title":"penatibus et magnis","map":"9bL6Goizl0vp", "starCount":Math.floor(Math.random() * 11)},
{"title":"ipsum dolor sit amet consectetuer","map":"49TGoZ", "starCount":Math.floor(Math.random() * 11)},
{"title":"donec quis","map":"chiSvr", "starCount":Math.floor(Math.random() * 11)},
{"title":"vulputate luctus cum","map":"eD6glx", "starCount":Math.floor(Math.random() * 11)},
{"title":"ligula sit amet","map":"ZsCUpGLRcz1m", "starCount":Math.floor(Math.random() * 11)},
{"title":"quam fringilla rhoncus mauris enim","map":"Z8xueA9Up", "starCount":Math.floor(Math.random() * 11)},
{"title":"curae mauris viverra","map":"9zX5zz", "starCount":Math.floor(Math.random() * 11)},
{"title":"turpis enim","map":"A3z4OsWfOk", "starCount":Math.floor(Math.random() * 11)},
{"title":"natoque penatibus et magnis","map":"IVhYrZ", "starCount":Math.floor(Math.random() * 11)},
{"title":"placerat","map":"3IM9aWCUI", "starCount":Math.floor(Math.random() * 11)},
{"title":"nulla dapibus dolor vel est","map":"Y1WUMw", "starCount":Math.floor(Math.random() * 11)},
{"title":"lacinia","map":"NBlu9zT6kUC", "starCount":Math.floor(Math.random() * 11)},
{"title":"iaculis justo","map":"dFt8vJ", "starCount":Math.floor(Math.random() * 11)},
{"title":"consequat metus sapien ut nunc","map":"TEP30qwuRp", "starCount":Math.floor(Math.random() * 11)},
{"title":"amet nulla","map":"RAB2Bgkul", "starCount":Math.floor(Math.random() * 11)},
{"title":"habitasse platea dictumst maecenas","map":"JZ6zCM", "starCount":Math.floor(Math.random() * 11)},
{"title":"scelerisque mauris","map":"hoSHCm7SfvYY", "starCount":Math.floor(Math.random() * 11)},
{"title":"primis in","map":"SuNWx0wWe", "starCount":Math.floor(Math.random() * 11)},
{"title":"nec euismod scelerisque","map":"34vOkHZGE", "starCount":Math.floor(Math.random() * 11)},
{"title":"blandit mi in","map":"WVgjIe", "starCount":Math.floor(Math.random() * 11)},
{"title":"at nunc commodo placerat praesent","map":"bsgnrSrd7", "starCount":Math.floor(Math.random() * 11)},
{"title":"facilisi","map":"0RHCacScfFL", "starCount":Math.floor(Math.random() * 11)},
{"title":"volutpat in congue etiam","map":"T8p4oJSGA", "starCount":Math.floor(Math.random() * 11)},
{"title":"ut suscipit a feugiat et","map":"eYCOaMiUz", "starCount":Math.floor(Math.random() * 11)},
{"title":"gravida sem","map":"AVUVSXow", "starCount":Math.floor(Math.random() * 11)},
{"title":"rhoncus aliquam lacus morbi quis","map":"qkJa8Bo", "starCount":Math.floor(Math.random() * 11)},
{"title":"aliquet pulvinar sed nisl nunc","map":"8vqKRxvbw", "starCount":Math.floor(Math.random() * 11)},
{"title":"montes nascetur ridiculus mus vivamus","map":"DorOnE9pV", "starCount":Math.floor(Math.random() * 11)},
{"title":"vivamus","map":"Gzf2daleZD", "starCount":Math.floor(Math.random() * 11)},
{"title":"magnis dis","map":"4KOR1iiWY", "starCount":Math.floor(Math.random() * 11)},
{"title":"nulla integer pede justo","map":"wmggppEnytIs", "starCount":Math.floor(Math.random() * 11)},
{"title":"ut","map":"dgra9Adf", "starCount":Math.floor(Math.random() * 11)},
{"title":"elementum in hac habitasse platea","map":"9hlw0gc", "starCount":Math.floor(Math.random() * 11)},
{"title":"habitasse platea dictumst","map":"AdQLYV", "starCount":Math.floor(Math.random() * 11)},
{"title":"at vulputate vitae nisl aenean","map":"0QHfPYnybU", "starCount":Math.floor(Math.random() * 11)},
{"title":"natoque penatibus et magnis","map":"xqnbZwkH", "starCount":Math.floor(Math.random() * 11)},
{"title":"potenti cras in purus","map":"FEZlI1", "starCount":Math.floor(Math.random() * 11)},
{"title":"praesent lectus vestibulum","map":"0vhbpEtR", "starCount":Math.floor(Math.random() * 11)},
{"title":"ornare imperdiet sapien","map":"HQpJ8b", "starCount":Math.floor(Math.random() * 11)},
{"title":"donec quis","map":"CSMlmeZZk", "starCount":Math.floor(Math.random() * 11)},
{"title":"magna vestibulum","map":"Y3x76wJr2", "starCount":Math.floor(Math.random() * 11)},
{"title":"vestibulum","map":"JfgXnw1l", "starCount":Math.floor(Math.random() * 11)},
{"title":"ultrices phasellus id sapien","map":"NLfGV2Vdd1", "starCount":Math.floor(Math.random() * 11)},
{"title":"sed vel enim","map":"Due6t1khiDc", "starCount":Math.floor(Math.random() * 11)},
{"title":"auctor gravida sem praesent id","map":"8Lb025QeB", "starCount":Math.floor(Math.random() * 11)},
{"title":"amet","map":"7ZnYx6fnB5tD", "starCount":Math.floor(Math.random() * 11)},
{"title":"in felis donec semper","map":"F6KZoLGCJQEt", "starCount":Math.floor(Math.random() * 11)},
{"title":"diam id ornare imperdiet","map":"PLWfASB", "starCount":Math.floor(Math.random() * 11)},
{"title":"ultricies","map":"oI20MuJQh2", "starCount":Math.floor(Math.random() * 11)},
{"title":"eget elit","map":"zr17DeEKK", "starCount":Math.floor(Math.random() * 11)},
{"title":"in eleifend quam","map":"2RxBdHCsl8M3", "starCount":Math.floor(Math.random() * 11)},
{"title":"sodales","map":"9kXfq0zZ", "starCount":Math.floor(Math.random() * 11)},
{"title":"parturient montes","map":"DTNeiLHSpSbq", "starCount":Math.floor(Math.random() * 11)},
{"title":"sed nisl nunc","map":"j1CoAivz", "starCount":Math.floor(Math.random() * 11)},
{"title":"quis libero","map":"O1yqsrA38n", "starCount":Math.floor(Math.random() * 11)},
{"title":"dictumst morbi vestibulum","map":"7Hcv6C0l", "starCount":Math.floor(Math.random() * 11)},
{"title":"in purus eu magna vulputate","map":"klcquW", "starCount":Math.floor(Math.random() * 11)},
{"title":"integer aliquet","map":"aL07VpRc1r", "starCount":Math.floor(Math.random() * 11)},
{"title":"malesuada in imperdiet et","map":"wxCklM78DP", "starCount":Math.floor(Math.random() * 11)},
{"title":"ultrices posuere cubilia","map":"YlMvFxJWSAfp", "starCount":Math.floor(Math.random() * 11)},
{"title":"vel est","map":"d6G27KeF", "starCount":Math.floor(Math.random() * 11)},
{"title":"est et","map":"tr4La9", "starCount":Math.floor(Math.random() * 11)},
{"title":"mauris ullamcorper purus","map":"g0RMM1s", "starCount":Math.floor(Math.random() * 11)},
{"title":"amet turpis elementum ligula","map":"a6c81QuX", "starCount":Math.floor(Math.random() * 11)},
{"title":"imperdiet nullam orci","map":"dJoH9SqwLF5n", "starCount":Math.floor(Math.random() * 11)},
{"title":"sapien","map":"HMHVi18c", "starCount":Math.floor(Math.random() * 11)},
{"title":"sagittis dui vel","map":"AFqy51", "starCount":Math.floor(Math.random() * 11)},
{"title":"magnis","map":"PjAapPT5N", "starCount":Math.floor(Math.random() * 11)},
{"title":"augue vel accumsan tellus nisi","map":"lrJpq0mSq4M", "starCount":Math.floor(Math.random() * 11)},
{"title":"in tempus","map":"6u7gIV", "starCount":Math.floor(Math.random() * 11)},
{"title":"dis parturient montes","map":"yB5mt0eR7BL", "starCount":Math.floor(Math.random() * 11)},
{"title":"magna vulputate","map":"EWfjsM1kh4", "starCount":Math.floor(Math.random() * 11)},
{"title":"nisi nam ultrices libero non","map":"4tXOTyZEaTOy", "starCount":Math.floor(Math.random() * 11)},
{"title":"ante ipsum","map":"7mqN1NGU", "starCount":Math.floor(Math.random() * 11)},
{"title":"blandit","map":"y73lCYsh", "starCount":Math.floor(Math.random() * 11)},
{"title":"dui","map":"e2Mc32HkO", "starCount":Math.floor(Math.random() * 11)},
{"title":"nulla","map":"Bj6UYds0Y", "starCount":Math.floor(Math.random() * 11)},
{"title":"pede venenatis","map":"C5PyL6", "starCount":Math.floor(Math.random() * 11)},
{"title":"adipiscing","map":"2lJ6f6", "starCount":Math.floor(Math.random() * 11)},
{"title":"sit amet","map":"N8PaonSr", "starCount":Math.floor(Math.random() * 11)},
{"title":"est risus auctor sed tristique","map":"N8F2j2", "starCount":Math.floor(Math.random() * 11)},
{"title":"turpis donec posuere metus vitae","map":"0h3dgnt", "starCount":Math.floor(Math.random() * 11)},
{"title":"donec vitae nisi nam ultrices","map":"mSUmqV", "starCount":Math.floor(Math.random() * 11)},
{"title":"nam ultrices libero non mattis","map":"mTh53Alq", "starCount":Math.floor(Math.random() * 11)},
{"title":"luctus cum","map":"7KNFVk9JQ9g", "starCount":Math.floor(Math.random() * 11)},
{"title":"cras","map":"94SO1OJ3t", "starCount":Math.floor(Math.random() * 11)},
{"title":"non velit donec diam","map":"kGKGNTxL", "starCount":Math.floor(Math.random() * 11)},
{"title":"ultricies eu nibh quisque id","map":"d1suaVw", "starCount":Math.floor(Math.random() * 11)},
{"title":"neque libero convallis eget","map":"mKl6hxsU", "starCount":Math.floor(Math.random() * 11)},
{"title":"libero quis","map":"FipyX2r", "starCount":Math.floor(Math.random() * 11)},
{"title":"quam pharetra","map":"iazbObsW", "starCount":Math.floor(Math.random() * 11)},
{"title":"non mattis pulvinar nulla","map":"leLrenyy", "starCount":Math.floor(Math.random() * 11)},
{"title":"ultrices","map":"wr3skKwYLbDO", "starCount":Math.floor(Math.random() * 11)},
{"title":"nibh ligula nec sem","map":"se3ezj7C56wp", "starCount":Math.floor(Math.random() * 11)},
{"title":"eget tincidunt eget tempus vel","map":"sFewxaF1Kr", "starCount":Math.floor(Math.random() * 11)},
{"title":"nulla ac enim in tempor","map":"HyHVCq", "starCount":Math.floor(Math.random() * 11)},
{"title":"condimentum curabitur in","map":"NRgQVFzZPaEB", "starCount":Math.floor(Math.random() * 11)},
{"title":"nisl aenean lectus","map":"4NL1BCaT5", "starCount":Math.floor(Math.random() * 11)},
{"title":"in magna bibendum","map":"0hKcYF", "starCount":Math.floor(Math.random() * 11)},
{"title":"vel est donec odio justo","map":"XG1Ric5J", "starCount":Math.floor(Math.random() * 11)},
{"title":"volutpat","map":"tzAxPxGM", "starCount":Math.floor(Math.random() * 11)},
{"title":"suspendisse potenti nullam porttitor lacus","map":"X5qFHw3i2Jv2", "starCount":Math.floor(Math.random() * 11)},
{"title":"ultrices posuere","map":"rsSXEwW", "starCount":Math.floor(Math.random() * 11)},
{"title":"eu sapien cursus","map":"n9MIpxwIUGdD", "starCount":Math.floor(Math.random() * 11)},
{"title":"nunc proin at turpis a","map":"qMOBZjdPr1J", "starCount":Math.floor(Math.random() * 11)},
{"title":"sed justo pellentesque","map":"bPwxcUqO", "starCount":Math.floor(Math.random() * 11)},
{"title":"ut ultrices","map":"isfc1lkdzcFz", "starCount":Math.floor(Math.random() * 11)},
{"title":"justo","map":"e1TRvKeQgP", "starCount":Math.floor(Math.random() * 11)},
{"title":"primis","map":"f4LTFUFEX", "starCount":Math.floor(Math.random() * 11)},
{"title":"diam erat","map":"j5Tzz0", "starCount":Math.floor(Math.random() * 11)},
{"title":"morbi porttitor lorem id","map":"fWpMKvIH", "starCount":Math.floor(Math.random() * 11)},
{"title":"viverra eget congue","map":"ao0JSscb32Sa", "starCount":Math.floor(Math.random() * 11)},
{"title":"erat tortor sollicitudin mi","map":"siIfzkuzxa", "starCount":Math.floor(Math.random() * 11)},
{"title":"et","map":"UDz12ZoZ5NOt", "starCount":Math.floor(Math.random() * 11)},
{"title":"at nibh","map":"vea7GmV6muT", "starCount":Math.floor(Math.random() * 11)},
{"title":"eget elit","map":"HulyfQt", "starCount":Math.floor(Math.random() * 11)},
{"title":"condimentum neque sapien placerat","map":"KIICM83", "starCount":Math.floor(Math.random() * 11)},
{"title":"vel","map":"ejGobQpe", "starCount":Math.floor(Math.random() * 11)},
{"title":"volutpat","map":"NdzunY7pHp", "starCount":Math.floor(Math.random() * 11)},
{"title":"pretium","map":"iz0T71mNUIm", "starCount":Math.floor(Math.random() * 11)},
{"title":"ante ipsum primis in faucibus","map":"nk4egMny", "starCount":Math.floor(Math.random() * 11)},
{"title":"faucibus orci","map":"AfQSh5d4f", "starCount":Math.floor(Math.random() * 11)},
{"title":"sapien urna pretium nisl ut","map":"1u9rzy", "starCount":Math.floor(Math.random() * 11)},
{"title":"sem duis aliquam convallis","map":"DQJCiOZaysxq", "starCount":Math.floor(Math.random() * 11)},
{"title":"varius ut blandit non","map":"ZuxEPd", "starCount":Math.floor(Math.random() * 11)},
{"title":"sapien varius ut","map":"Wzq0nu", "starCount":Math.floor(Math.random() * 11)},
{"title":"odio elementum eu interdum","map":"j6R00EvXV", "starCount":Math.floor(Math.random() * 11)},
{"title":"sollicitudin","map":"ONNA6Wbq8", "starCount":Math.floor(Math.random() * 11)},
{"title":"tincidunt nulla mollis molestie lorem","map":"beHZkfov2h", "starCount":Math.floor(Math.random() * 11)},
{"title":"condimentum","map":"Pjinj4Re", "starCount":Math.floor(Math.random() * 11)},
{"title":"eget","map":"431jz9", "starCount":Math.floor(Math.random() * 11)},
{"title":"congue risus semper","map":"L2KPPa1bY", "starCount":Math.floor(Math.random() * 11)},
{"title":"dui","map":"wcOkBIf4bZ", "starCount":Math.floor(Math.random() * 11)},
{"title":"aliquam","map":"Cb82q5nfvG2t", "starCount":Math.floor(Math.random() * 11)},
{"title":"consequat metus sapien ut nunc","map":"dovpRgS9wxJw", "starCount":Math.floor(Math.random() * 11)},
{"title":"viverra diam vitae quam","map":"e4AoT5iDl", "starCount":Math.floor(Math.random() * 11)},
{"title":"nam ultrices libero non mattis","map":"RC7JpKa", "starCount":Math.floor(Math.random() * 11)},
{"title":"sit","map":"zWTC4gmqcXS0", "starCount":Math.floor(Math.random() * 11)},
{"title":"non quam","map":"g0Wpeez", "starCount":Math.floor(Math.random() * 11)},
{"title":"maecenas leo odio condimentum","map":"lUhh8WVKm", "starCount":Math.floor(Math.random() * 11)},
{"title":"luctus rutrum nulla","map":"oi6QGwK", "starCount":Math.floor(Math.random() * 11)},
{"title":"a","map":"ZDRlI3fBM6t6", "starCount":Math.floor(Math.random() * 11)},
{"title":"ligula","map":"jJ73hpvTNROt", "starCount":Math.floor(Math.random() * 11)},
{"title":"eu","map":"tG8jyXFJrmQ", "starCount":Math.floor(Math.random() * 11)},
{"title":"at turpis donec","map":"vvorVxw", "starCount":Math.floor(Math.random() * 11)},
{"title":"praesent blandit lacinia erat","map":"pfQrEs", "starCount":Math.floor(Math.random() * 11)},
{"title":"morbi sem mauris laoreet ut","map":"pcPjibeu", "starCount":Math.floor(Math.random() * 11)},
{"title":"odio","map":"HZmiDBvWm", "starCount":Math.floor(Math.random() * 11)},
{"title":"accumsan odio curabitur convallis","map":"2eUQWPcdpT", "starCount":Math.floor(Math.random() * 11)},
{"title":"proin leo odio porttitor id","map":"sQlPYYi", "starCount":Math.floor(Math.random() * 11)},
{"title":"ipsum dolor sit amet consectetuer","map":"4aJcAw9WKx3V", "starCount":Math.floor(Math.random() * 11)},
{"title":"eu","map":"PQO7VsHjJXV", "starCount":Math.floor(Math.random() * 11)},
{"title":"mattis odio","map":"1trJmnWz", "starCount":Math.floor(Math.random() * 11)},
{"title":"lobortis ligula","map":"Z5avIFaXLR", "starCount":Math.floor(Math.random() * 11)},
{"title":"cursus vestibulum","map":"s1QPUVOF6KD", "starCount":Math.floor(Math.random() * 11)},
{"title":"consequat in","map":"HddoCEw", "starCount":Math.floor(Math.random() * 11)},
{"title":"eu","map":"r940sBnhZpt", "starCount":Math.floor(Math.random() * 11)},
{"title":"ornare imperdiet","map":"Kf4IDu3uJ", "starCount":Math.floor(Math.random() * 11)},
{"title":"felis ut","map":"Ud3FST", "starCount":Math.floor(Math.random() * 11)},
{"title":"in quis justo maecenas rhoncus","map":"uJQ3auedzbB", "starCount":Math.floor(Math.random() * 11)},
{"title":"sit amet turpis elementum","map":"bblqS8O6", "starCount":Math.floor(Math.random() * 11)},
{"title":"lorem","map":"FvtvL8jopC15", "starCount":Math.floor(Math.random() * 11)},
{"title":"rutrum nulla tellus","map":"fi788AEjDh", "starCount":Math.floor(Math.random() * 11)},
{"title":"dui","map":"ps24YinKFl", "starCount":Math.floor(Math.random() * 11)},
{"title":"in purus","map":"VEVsrmMhq", "starCount":Math.floor(Math.random() * 11)},
{"title":"maecenas tincidunt lacus at velit","map":"QpY45Zh", "starCount":Math.floor(Math.random() * 11)},
{"title":"a suscipit nulla elit","map":"i37f1tPGGe", "starCount":Math.floor(Math.random() * 11)},
{"title":"curae donec pharetra magna","map":"mwKKwarAjtj", "starCount":Math.floor(Math.random() * 11)},
{"title":"morbi non lectus aliquam","map":"Cr2fFEygU", "starCount":Math.floor(Math.random() * 11)},
{"title":"nisl aenean lectus pellentesque eget","map":"VYMZXavkIxbS", "starCount":Math.floor(Math.random() * 11)},
{"title":"pede ac diam","map":"U1CF8cciI4h1", "starCount":Math.floor(Math.random() * 11)},
{"title":"luctus rutrum nulla tellus in","map":"7lL75wn3wBEu", "starCount":Math.floor(Math.random() * 11)},
{"title":"porttitor pede justo eu","map":"fYe1t5Y", "starCount":Math.floor(Math.random() * 11)},
{"title":"semper rutrum nulla","map":"MOqQH8", "starCount":Math.floor(Math.random() * 11)},
{"title":"id sapien","map":"15Ng90", "starCount":Math.floor(Math.random() * 11)},
{"title":"ut","map":"xwdE5FTC00V", "starCount":Math.floor(Math.random() * 11)},
{"title":"interdum","map":"anjCSa", "starCount":Math.floor(Math.random() * 11)},
{"title":"tortor","map":"RDIM18dM", "starCount":Math.floor(Math.random() * 11)},
{"title":"in quis justo maecenas","map":"G4L1o13s", "starCount":Math.floor(Math.random() * 11)},
{"title":"suspendisse","map":"o87ZnOtD0", "starCount":Math.floor(Math.random() * 11)},
{"title":"enim","map":"kU9cuhWrh5f4", "starCount":Math.floor(Math.random() * 11)},
{"title":"justo in blandit","map":"209sQ5Ha", "starCount":Math.floor(Math.random() * 11)},
{"title":"turpis sed ante vivamus","map":"KQ7VTqxM21", "starCount":Math.floor(Math.random() * 11)},
{"title":"mollis molestie lorem quisque","map":"btLf9Yxltqds", "starCount":Math.floor(Math.random() * 11)},
{"title":"magna vestibulum","map":"i6IWgB0ku", "starCount":Math.floor(Math.random() * 11)},
{"title":"maecenas rhoncus","map":"6FkhLH", "starCount":Math.floor(Math.random() * 11)},
{"title":"ac nibh fusce lacus","map":"dooaQqkzheN", "starCount":Math.floor(Math.random() * 11)},
{"title":"blandit ultrices enim lorem","map":"vZcDOahCOU", "starCount":Math.floor(Math.random() * 11)},
{"title":"velit vivamus vel","map":"cPFddlkiaYJ", "starCount":Math.floor(Math.random() * 11)},
{"title":"in","map":"qgwNUh", "starCount":Math.floor(Math.random() * 11)},
{"title":"lobortis sapien sapien non mi","map":"KlE00Dy7Wi", "starCount":Math.floor(Math.random() * 11)},
{"title":"semper porta volutpat quam pede","map":"6gONqOTPrI", "starCount":Math.floor(Math.random() * 11)},
{"title":"nulla nunc purus","map":"UpwoeQmp", "starCount":Math.floor(Math.random() * 11)},
{"title":"eget orci","map":"RYSGaAhWoaLd", "starCount":Math.floor(Math.random() * 11)},
{"title":"lectus pellentesque at nulla","map":"cfsU2xNenI1", "starCount":Math.floor(Math.random() * 11)},
{"title":"vestibulum ante ipsum primis","map":"pKfCD13oUvKz", "starCount":Math.floor(Math.random() * 11)},
{"title":"ultrices","map":"Qm80AawcVy0f", "starCount":Math.floor(Math.random() * 11)},
{"title":"morbi quis","map":"aOcmv2ki", "starCount":Math.floor(Math.random() * 11)},
{"title":"accumsan","map":"sReuHxeXpG", "starCount":Math.floor(Math.random() * 11)},
{"title":"aenean","map":"ej102kz", "starCount":Math.floor(Math.random() * 11)},
{"title":"integer","map":"QF5kbx", "starCount":Math.floor(Math.random() * 11)},
{"title":"ut","map":"mova3A", "starCount":Math.floor(Math.random() * 11)},
{"title":"lacinia","map":"cJ3elpqze22", "starCount":Math.floor(Math.random() * 11)},
{"title":"est","map":"VJfvrurnQ", "starCount":Math.floor(Math.random() * 11)},
{"title":"integer a nibh","map":"lIQS6hPZX", "starCount":Math.floor(Math.random() * 11)},
{"title":"id ornare","map":"ucvt5llL1W", "starCount":Math.floor(Math.random() * 11)},
{"title":"libero convallis eget eleifend luctus","map":"Xg45am", "starCount":Math.floor(Math.random() * 11)},
{"title":"pellentesque eget nunc donec","map":"FSZTIy", "starCount":Math.floor(Math.random() * 11)},
{"title":"habitasse platea","map":"1FFzkxm0n", "starCount":Math.floor(Math.random() * 11)},
{"title":"turpis a pede","map":"5h6DRsQouTfx", "starCount":Math.floor(Math.random() * 11)},
{"title":"amet nulla","map":"bkxzrE3cSv", "starCount":Math.floor(Math.random() * 11)},
{"title":"faucibus cursus","map":"YpCiZHitz0uL", "starCount":Math.floor(Math.random() * 11)},
{"title":"sollicitudin mi sit amet lobortis","map":"lH9TfkllpJr1", "starCount":Math.floor(Math.random() * 11)},
{"title":"turpis","map":"hsPzvEAkYxP", "starCount":Math.floor(Math.random() * 11)},
{"title":"amet consectetuer adipiscing elit","map":"m009yihzL", "starCount":Math.floor(Math.random() * 11)},
{"title":"turpis nec euismod scelerisque quam","map":"xgbELkodzV", "starCount":Math.floor(Math.random() * 11)},
{"title":"penatibus et magnis dis parturient","map":"Myxw3lv", "starCount":Math.floor(Math.random() * 11)},
{"title":"tristique in","map":"VIqfiRRvFC25", "starCount":Math.floor(Math.random() * 11)},
{"title":"purus","map":"teeyR9LL", "starCount":Math.floor(Math.random() * 11)},
{"title":"turpis donec posuere metus vitae","map":"dV28XqpZ", "starCount":Math.floor(Math.random() * 11)},
{"title":"tellus in sagittis dui","map":"cUl589NV9909", "starCount":Math.floor(Math.random() * 11)},
{"title":"vestibulum ac est","map":"Q4vxbEYg", "starCount":Math.floor(Math.random() * 11)},
{"title":"cras mi pede malesuada","map":"janCQ0T7HQg", "starCount":Math.floor(Math.random() * 11)},
{"title":"pede posuere nonummy integer","map":"XHxsYhtcPD", "starCount":Math.floor(Math.random() * 11)},
{"title":"vestibulum ac est lacinia","map":"fiTCjkprNsX", "starCount":Math.floor(Math.random() * 11)},
{"title":"sem duis aliquam convallis","map":"iCfMsj7c4", "starCount":Math.floor(Math.random() * 11)},
{"title":"dolor sit","map":"65Sh1cGdy", "starCount":Math.floor(Math.random() * 11)},
{"title":"ligula sit amet","map":"CQsIVjXkMNh3", "starCount":Math.floor(Math.random() * 11)},
{"title":"malesuada in","map":"EkxOsEd", "starCount":Math.floor(Math.random() * 11)},
{"title":"in faucibus orci","map":"ZdkdLSOJp5N", "starCount":Math.floor(Math.random() * 11)},
{"title":"sit","map":"Dj6Dr6OOs0Ox", "starCount":Math.floor(Math.random() * 11)},
{"title":"erat tortor sollicitudin mi","map":"WkGXn9n5X", "starCount":Math.floor(Math.random() * 11)},
{"title":"donec pharetra","map":"J3aba8EGDT", "starCount":Math.floor(Math.random() * 11)},
{"title":"justo in hac habitasse platea","map":"ov6DiaqC0BQ", "starCount":Math.floor(Math.random() * 11)},
{"title":"nunc purus phasellus","map":"TEvMiKcSQAB", "starCount":Math.floor(Math.random() * 11)},
{"title":"accumsan tellus","map":"9hlKbE8OKH", "starCount":Math.floor(Math.random() * 11)},
{"title":"tellus in sagittis","map":"e1IcYT3tr", "starCount":Math.floor(Math.random() * 11)},
{"title":"sapien","map":"B48u9w", "starCount":Math.floor(Math.random() * 11)},
{"title":"elementum ligula","map":"Uhe1pP4wTIQN", "starCount":Math.floor(Math.random() * 11)},
{"title":"morbi non lectus aliquam","map":"bZIDB4A6KJ", "starCount":Math.floor(Math.random() * 11)},
{"title":"proin leo odio","map":"83mzoS", "starCount":Math.floor(Math.random() * 11)},
{"title":"metus sapien ut nunc","map":"GPG7BHRh", "starCount":Math.floor(Math.random() * 11)},
{"title":"ipsum dolor sit","map":"zrvh3Fa40", "starCount":Math.floor(Math.random() * 11)},
{"title":"id consequat in","map":"ixu2bQ64d3y8", "starCount":Math.floor(Math.random() * 11)},
{"title":"urna pretium nisl","map":"WvDOaUOc", "starCount":Math.floor(Math.random() * 11)},
{"title":"tempus vivamus in","map":"z0BzSG9HD", "starCount":Math.floor(Math.random() * 11)},
{"title":"ultrices erat tortor sollicitudin mi","map":"Lw18xB68a", "starCount":Math.floor(Math.random() * 11)},
{"title":"diam","map":"FylKPpAZVH", "starCount":Math.floor(Math.random() * 11)},
{"title":"sollicitudin mi sit","map":"2t0Bm7Bj6", "starCount":Math.floor(Math.random() * 11)},
{"title":"libero","map":"9OUj0q1E8XD", "starCount":Math.floor(Math.random() * 11)},
{"title":"augue","map":"tkQZTvU", "starCount":Math.floor(Math.random() * 11)},
{"title":"aliquet pulvinar","map":"id3Yuu7d9pC", "starCount":Math.floor(Math.random() * 11)},
{"title":"in imperdiet et commodo vulputate","map":"nkaTUqoXWN1i", "starCount":Math.floor(Math.random() * 11)},
{"title":"lectus in quam fringilla","map":"cjzv23Q6t", "starCount":Math.floor(Math.random() * 11)},
{"title":"augue aliquam erat","map":"h2dX56rhmc1", "starCount":Math.floor(Math.random() * 11)},
{"title":"aliquet","map":"RfEe0x", "starCount":Math.floor(Math.random() * 11)},
{"title":"quis orci","map":"lIlcpNmAYN", "starCount":Math.floor(Math.random() * 11)},
{"title":"sit amet consectetuer","map":"HzdzVdb", "starCount":Math.floor(Math.random() * 11)},
{"title":"volutpat convallis morbi odio odio","map":"LtZUACrbo", "starCount":Math.floor(Math.random() * 11)},
{"title":"pellentesque ultrices mattis odio","map":"eBzSaE", "starCount":Math.floor(Math.random() * 11)},
{"title":"erat curabitur gravida","map":"t154B1Jk53s", "starCount":Math.floor(Math.random() * 11)},
{"title":"integer a","map":"6HTYqSs", "starCount":Math.floor(Math.random() * 11)},
{"title":"metus","map":"IrkGQJEPMkY", "starCount":Math.floor(Math.random() * 11)},
{"title":"at vulputate","map":"IdZIKD", "starCount":Math.floor(Math.random() * 11)},
{"title":"lacus","map":"7GTZvn", "starCount":Math.floor(Math.random() * 11)}];

//fake data at top because of hoisting issues
const mongoose = require('mongoose');
const Promise = require('bluebird');
const connectToDb = require('./index.js');
const User = mongoose.model('User');
const Level = mongoose.model('Level');

connectToDb.then(function() {
	var before = Date.now();
	User.create(fakeUsers).then(function() {
		console.log(Date.now() - before);
		var matchedGamesToUsers = fakeLevels.map(function(level) {
			return User.findOne({name: fakeUsers[Math.floor(Math.random() * fakeUsers.length)].name})
			.then(function(foundUser) {
				level.creator = foundUser._id;
				return level;
			});
		})
		return Promise.all(matchedGamesToUsers);
	})
	.then(function(levelArr) {
		return Level.create(levelArr);
	}).then(function() {
		console.log('seeded');
		console.log(Date.now() - before);
		process.kill(0);
	}).then(null, function(e) {
		console.error(e);
		process.kill(0);
	});
});
